---
- name: Task - Storing passwords
  hosts: all
  var_files:
    - passwds.yml
  tasks:
    - name: say hello
      become: yes
      ansible_become_pass: "{{ pass1 }}"
      shell: 
        cmd: sudo echo "Hello"
